[project]
name = "tcs-garr"
version = "0.24.0"
description = "Command-line tool to manage and interact with Harica platform"
readme = "README.md"
license = { text = "GPL-3.0-or-later" }
requires-python = ">=3.9"
dynamic = ["dependencies", "classifiers"]
authors = [{ name = "Consortium GARR", email = "system.support@garr.it" }]
maintainers = [{ name = "Consortium GARR", email = "system.support@garr.it" }]

[project.urls]
Documentation = "https://github.com/ConsortiumGARR/tcs-garr/blob/main/README.md"
Repository = "https://github.com/ConsortiumGARR/tcs-garr"
Changelog = "https://github.com/ConsortiumGARR/tcs-garr/blob/main/CHANGELOG.md"

[project.scripts]
tcs-garr = "tcs_garr.main:main"

[tool.poetry]
include = ["chain/**"]

[tool.poetry.dependencies]
python = ">3.9.0,<3.9.1 || >3.9.1,<4.0"
cryptography = "^45.0.3"
tabulate = "^0.9.0"
pytz = "^2025.2"
colorama = "^0.4.6"
python-dateutil = "^2.9.0.post0"
beautifulsoup4 = "^4.13.4"
requests = "^2.32.3"
pyotp = "^2.9.0"
jwt = "^1.3.1"
packaging = "^25.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.11.11"
pre-commit = "^4.2.0"
commitizen = "^4.8.2"

[tool.ruff]
# Exclude common directories that are typically not part of the source code or are generated by tools.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "business-facing/layer", #OKAPI Layer
]

# Set the maximum line length to 127 characters.
line-length = 127

# Define the number of spaces used for indentation, aligning with Black's style.
indent-width = 4


[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver2"
version_provider = "pep621"
update_changelog_on_bump = true
major_version_zero = true
version_files = ["README.md"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
